---
abstract: 'Client for the Pocket api (http://getpocket.com/api/)'
author:
  - 'William Wolf <throughnothing@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120630'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Pocket
requires:
  Data::Dumper: 0
  HTTP::Tiny: 0
  JSON: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/throughnothing/WebService-Pocket/issues
  repository: git://github.com/throughnothing/WebService-Pocket.git
version: 0.001
