---
abstract: 'Client for the Pocket api (http://getpocket.com/api/)'
author:
  - 'William Wolf <throughnothing@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Pocket
requires:
  Data::Dumper: 0
  DateTime: 0
  HTTP::Tiny: 0.014
  JSON: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt: 0.48
  MooseX::SimpleConfig: 0
  Net::SSLeay: 1.49
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com//WebService-Pocket.git
version: 0.003
x_contributors:
  - 'Andreas Marienborg <andreas.marienborg@gmail.com>'
  - 'Paul Fenwick <pjf@perltraining.com.au>'
  - 'ben hengst <notbenh@cpan.org>'
